// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkI64umffNLnZAJ7d_COVd3hX4jOz2u_U',
    appId: '1:939117825264:web:ce54cd97fd831690418635',
    messagingSenderId: '939117825264',
    projectId: 'chatx-3d9fd',
    authDomain: 'chatx-3d9fd.firebaseapp.com',
    storageBucket: 'chatx-3d9fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpNrNb_-gStEh_T6aETNAwztbbwa6xmhc',
    appId: '1:939117825264:android:f47ff3940771d0a8418635',
    messagingSenderId: '939117825264',
    projectId: 'chatx-3d9fd',
    storageBucket: 'chatx-3d9fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1RpONuFRBeRtI2FNHdbWiQdzS3mNw8UQ',
    appId: '1:939117825264:ios:cf3a3c1672ccdd94418635',
    messagingSenderId: '939117825264',
    projectId: 'chatx-3d9fd',
    storageBucket: 'chatx-3d9fd.appspot.com',
    iosBundleId: 'com.example.chatx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1RpONuFRBeRtI2FNHdbWiQdzS3mNw8UQ',
    appId: '1:939117825264:ios:d4a0fccc126240f6418635',
    messagingSenderId: '939117825264',
    projectId: 'chatx-3d9fd',
    storageBucket: 'chatx-3d9fd.appspot.com',
    iosBundleId: 'com.example.chatx.RunnerTests',
  );
}
